name: binder-badge
on:
  pull_request_target:

jobs:
  badge:
    runs-on: ubuntu-18.04
    steps:
      - uses: manics/action-binderbadge@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
