# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # Needed to use the conda environment.
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.8]

    steps:
    - uses: actions/checkout@v2
    # https://github.com/marketplace/actions/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Install dependencies with conda
      run: |
        conda info
        conda install --yes --file=requirements.txt
        conda list
    - name: Install package from setup.py
      run: |
        # This tests the setup process, but more importantly pytest wants the
        # package installed to run the test suite.
        python setup.py install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=89 --statistics
    - name: Run test suite with pytest
      run: |
        pytest -v tests
    - name: Type checking with mypy
      run: |
        mypy demes tests
