name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        # Needed to use the conda environment.
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.8]

    steps:
    - uses: actions/checkout@v2
    # https://github.com/marketplace/actions/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
    - name: Install dependencies
      run: |
        conda info
        # Building msprime on windows is nasty, so just install conda package
        # for all platforms for maximum simplicity. The version here should
        # be set to match that in the requirements.txt file.
        conda install --yes msprime==0.7.4
        conda list
        pip install -r requirements.txt
    - name: Run test suite with pytest
      run: |
        python -m pytest -v tests
